embed_assets: on
package_path: jammit

stylesheets:
  apidocs:
    - public/stylesheets/apidocs.css
  application:
    - public/stylesheets/application.css
  mobile:
    - public/stylesheets/mobile.css
  print:
    - public/stylesheets/print.css
  public:
    - public/stylesheets/public.css
  sessions:
    - public/stylesheets/sessions.css
  sites:
    - public/stylesheets/sessions.css
    - public/stylesheets/public.css
    - public/stylesheets/sites.css
  jQuery_widgets:
    - public/stylesheets/jQuery.Gantt/style.css
    - public/stylesheets/jQuery.Gantt/prettify.css
    - public/stylesheets/fullcalendar.css
